from pydantic import BaseModel

__all__ = [
    "UsuarioBase",
    "UsuarioCriar",
    "UsuarioAtualizar",
    "UsuarioResposta",
    "UsuarioLogin",
    "TokenResposta",
    "CategoriaBase",
    "CategoriaCriar",
    "CategoriaAtualizar",
    "CategoriaResposta",
    "LivroBase",
    "LivroCriar",
    "LivroAtualizar",
    "LivroResposta",
    "LoteBase",
    "LoteCriar",
    "LoteAtualizar",
    "LoteResposta",
    "MovimentacaoBase",
    "MovimentacaoCriar",
    "MovimentacaoAtualizar",
    "MovimentacaoResposta",
    "FilialBase",
    "FilialCriar",
    "FilialAtualizar",
    "FilialResposta",
    "AlertaMinimoResposta",
]
